--- #YAML:1.0
name:               Class-StateMachine
version:            0.19
abstract:           define classes for state machines
author:
    - Salvador Fandino <sfandino@yahoo.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Devel::Peek:     0
    Hash::Util:      0
    mro:             0
    MRO::Define:     0.01
    Package::Stash:  0.29
    Scalar::Util:    0
    Sub::Name:       0.05
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
